//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStore.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int Id { get; set; }
        public decimal Total { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual User Customer { get; set; }
    }
}
