//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStore.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Orders = new HashSet<Order>();
            this.Roles = new HashSet<Role>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public byte[] Revision { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual LoginCredential LoginCredential { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
